// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP6n7qG6bUI8j1Pr6_nZLDEhz5IXs1Tc0',
    appId: '1:861592838025:web:1a2475bf02372c0af0cb58',
    messagingSenderId: '861592838025',
    projectId: 'sporty-2ef60',
    authDomain: 'sporty-2ef60.firebaseapp.com',
    storageBucket: 'sporty-2ef60.firebasestorage.app',
    measurementId: 'G-JBB7MD34L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw4n2L--2Ki7rGOncxJ-BmYB-EJqOjp2g',
    appId: '1:861592838025:android:e5391b4a39209bf5f0cb58',
    messagingSenderId: '861592838025',
    projectId: 'sporty-2ef60',
    storageBucket: 'sporty-2ef60.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP6n7qG6bUI8j1Pr6_nZLDEhz5IXs1Tc0',
    appId: '1:861592838025:web:0a48cc225fb182caf0cb58',
    messagingSenderId: '861592838025',
    projectId: 'sporty-2ef60',
    authDomain: 'sporty-2ef60.firebaseapp.com',
    storageBucket: 'sporty-2ef60.firebasestorage.app',
    measurementId: 'G-VVT6TRK36Y',
  );
}
